notifications:
  email:
    on_success: never 
    on_failure: never 

language: php
php:
  - 7.3
  - 7.2
  - 7.1

before_script:
  - echo Start travis
  - wget https://scrutinizer-ci.com/ocular.phar
  - make composer-install
  - phpenv rehash

script:
  - make test
  
after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover